server:
  port: 8089

spring:
  datasource:
    # DB接続URL。localhost:3311に公開されたMySQLへ接続し、DB名はequip_loan。
    # allowPublicKeyRetrieval=trueは、MySQL 8以降でパスワード認証にRSA暗号化を使用するための設定。serverTimezone=Asia/Tokyoは、タイムゾーンの設定。
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3311}/equip_loan?allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
    # MySQLへ接続するユーザー名（docker-composeで作成したユーザー）
    username: ${MYSQL_USER:appuser}  
    # MySQLへ接続するパスワード（docker-composeのMYSQL_PASSWORD等と一致させる）
    password: ${MYSQL_PASSWORD:passw0rd}
  jpa:
    hibernate:
      # Hibernateに「DBを自動変更させない」設定。EntityとDBスキーマが一致しているか“検証だけ”する（不一致なら起動時にエラー）
      ddl-auto: validate
    show-sql: true
  flyway:
    # Flywayを有効化。起動時にdb/migrationのSQLを自動適用する
    enabled: true
    # マイグレーションSQLの置き場所。
    locations: classpath:db/migration